name       : onboard
version    : 1.4.1
release    : 7
source     :
    - https://launchpad.net/onboard/1.4/1.4.1/+download/onboard-1.4.1.tar.gz : 01cae1ac5b1ef1ab985bd2d2d79ded6fc99ee04b1535cc1bb191e43a231a3865
license    :
    - BSD-3-Clause
    - GPL-3.0-or-later
component  : desktop.library
summary    : On-screen keyboard
description: |
    Onboard is an onscreen keyboard useful for everybody that cannot use a
    hardware keyboard; for example TabletPC users, mobility impaired users
builddeps  :
    - pkgconfig(dconf)
    - pkgconfig(gdk-3.0)
    - pkgconfig(hunspell)
    - pkgconfig(libcanberra)
    - pkgconfig(python3)
    - pkgconfig(wayland-client)
    - pkgconfig(x11)
    - pkgconfig(xi)
    - pkgconfig(xkbcommon)
    - pkgconfig(xkbfile)
    - pkgconfig(xtst)
    - python-distutils-extra
rundeps    :
    - python3
setup      : |
    %patch -p1 < $pkgfiles/0001-data-Default-to-the-Nightshade-theme.patch
build      : |
    %python3_setup
install    : |
    %python3_install
    mv $installdir/etc/xdg $installdir/usr/share/.
    rmdir $installdir/etc
