name       : onboard
version    : 1.3.0
release    : 1
source     :
    - https://launchpad.net/onboard/1.3/1.3.0/+download/onboard-1.3.0.tar.gz : fd74b54b8bd7a075cf5f6e1a8ca3e6de5cd2663507adb690d7b1a85e71afa2e4
license    :
    - GPL-3.0
    - BSD-3-Clause
component  : desktop.library
summary    : On-screen keyboard
description: |
    Onboard is an onscreen keyboard useful for everybody that cannot use a
    hardware keyboard; for example TabletPC users, mobility impaired users
builddeps  :
    - pkgconfig(dconf)
    - pkgconfig(gdk-3.0)
    - pkgconfig(x11)
    - pkgconfig(xi)
    - pkgconfig(xtst)
    - pkgconfig(xkbfile)
    - pkgconfig(libcanberra)
    - pkgconfig(hunspell)
    - pkgconfig(python-3.5)
    - python-distutils-extra
rundeps    :
    - python3
build      : |
    %python3_setup   
install    : |
    %python3_install
    mv $installdir/etc/xdg $installdir/usr/share/.
    rmdir $installdir/etc
